apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: hello-rs
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: hello-world
  template:
      metadata:
        name: hello-world
        namespace: demo
        labels:
          env: dev
          app: hello-world
      spec:
        containers:
        - name: hello-world
          image: jinternals/hello-world:latest
          ports:
          - containerPort: 8080
            protocol: TCP
